# Generated by Django 3.1 on 2021-12-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'verbose_name': 'Абзац', 'verbose_name_plural': 'Абзацы'},
        ),
    ]
