# Generated by Django 3.1 on 2021-12-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20211210_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='main_banner',
        ),
        migrations.AddField(
            model_name='indexpage',
            name='main_banner',
            field=models.ManyToManyField(blank=True, null=True, to='index.MainBanner'),
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='reason',
        ),
        migrations.AddField(
            model_name='indexpage',
            name='reason',
            field=models.ManyToManyField(blank=True, null=True, to='index.Reason'),
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='indexpage',
            name='recommendation',
            field=models.ManyToManyField(blank=True, null=True, to='index.Recommendation'),
        ),
    ]
