# Generated by Django 3.1 on 2021-12-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20211210_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='main_banner',
            field=models.ManyToManyField(blank=True, to='index.MainBanner'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='reason',
            field=models.ManyToManyField(blank=True, to='index.Reason'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='recommendation',
            field=models.ManyToManyField(blank=True, to='index.Recommendation'),
        ),
    ]
