# Generated by Django 3.1 on 2021-12-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20211210_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='main_banner',
            field=models.ManyToManyField(blank=True, to='index.MainBanner', verbose_name='Абзацы'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='reason',
            field=models.ManyToManyField(blank=True, to='index.Reason', verbose_name='Причины'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='recommendation',
            field=models.ManyToManyField(blank=True, to='index.Recommendation', verbose_name='Рекомендации'),
        ),
    ]
