# Generated by Django 3.1 on 2021-12-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20211210_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reason',
            old_name='discrtiption',
            new_name='description',
        ),
    ]
