# Generated by Django 3.1 on 2021-12-10 05:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20211210_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержание'),
        ),
    ]
