# Generated by Django 3.1 on 2021-12-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_in',
            field=models.CharField(max_length=255, verbose_name='Въезд'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_out',
            field=models.CharField(max_length=255, verbose_name='Выезд'),
        ),
    ]
