# Generated by Django 3.1 on 2021-12-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20211211_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navigate',
        ),
    ]
