# Generated by Django 3.1 on 2021-12-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garpix_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comfort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Удобства')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Удосбтво',
                'verbose_name_plural': 'Удобства',
            },
        ),
        migrations.CreateModel(
            name='HotelsPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Отели',
                'verbose_name_plural': 'Отели',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepage',),
        ),
        migrations.CreateModel(
            name='OneHotelPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
                ('name', models.CharField(max_length=255, verbose_name='Название отеля')),
                ('type', models.CharField(choices=[('ГОСТИНИЦА', 'Гостиница'), ('МОТЕЛЬ', 'Мотель'), ('АПАРТАМЕНТЫ', 'Апартаменты')], max_length=255, verbose_name='Тип отеля')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Описание')),
                ('stars', models.PositiveIntegerField(blank=True, verbose_name='Звезды')),
                ('rating', models.FloatField(blank=True, verbose_name='Рейтинг')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('comfort', models.ManyToManyField(blank=True, to='hotels.Comfort', verbose_name='Удобства')),
            ],
            options={
                'verbose_name': 'Подробно Отель',
                'verbose_name_plural': 'Подробно Отели',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepage',),
        ),
    ]
