# Generated by Django 3.1 on 2021-12-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onehotelpage',
            name='name',
        ),
    ]
