# Generated by Django 3.1 on 2021-12-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_onehotelpage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onehotelpage',
            name='comfort',
            field=models.ManyToManyField(blank=True, related_name='comfort', to='hotels.Comfort', verbose_name='Удобства'),
        ),
    ]
