# Generated by Django 3.2.7 on 2021-11-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinfo',
            name='measure',
            field=models.CharField(default='грамм', max_length=30),
        ),
    ]
