# Generated by Django 3.2.7 on 2021-11-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_ingredientinfo_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='pizza.Tag'),
        ),
    ]
